### ISSUE TITLE
'Sentiment' gives assertion error

### ISSUE THREAD

**Issue by roughcoding** [hhsecond/corenlp_pywrap#1]
'Sentiment' annotator tag would not go through. Its throwing an assertion error saying "tag is not supported"

**Comment by hhsecond** [comment]
Beta version is released for current 'downloadable' version though Sentiment tag support is available in Github version of CoreNLP. Keeping this issue open until I fix it in ALPHA release.
Thanks

**Comment by hhsecond** [comment]
Issue is fixed in production/stable version
Sentiment is still not supported by downloadable version of CoreNLP. So sentiment tag is not inherently supported. You can do a hack to get it done. 
Described in README
